name: Build and Deploy to EKS

on:
  push:
    branches: [main]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: AKIAU6GDXKB64EMQTUQH
        aws-secret-access-key: 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
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Docker image
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k5u0o7b3
        docker build -t fadi-app .
        docker tag fadi-app:latest public.ecr.aws/k5u0o7b3/fadi-app:latest
        docker push public.ecr.aws/k5u0o7b3/fadi-app:latest
